### ISSUE TITLE
TextView doesn't show on iPhone X

### ISSUE THREAD

**Issue by majid701** [1amageek/Toolbar#4]
Making the toolbar anchored to the bottom of the screen doesn't work on iphone x!
Specifically the textview doesn't show, looks like something is wrong with the size of it.

![screen shot 2018-01-15 at 13 50 44](https://user-images.githubusercontent.com/15844600/34943274-4a331a98-f9fb-11e7-8472-8f83c6187853.png)

(Running example code in the screenshot above)

works fine on other devices.

Any solution?

**Comment by 1amageek** [comment]
Thank you for message.

I fixed it.

**Comment by majid701** [comment]
@1amageek You are amazing man!

I tested it and it works. This issue can be closed down.

**Comment by 1amageek** [comment]
@majid701 Hi. I changed the specification corresponding to iPhone X.

**Comment by majid701** [comment]
@1amageek the problem is back again for some reason!
Do I need to add some specific settings for iphone?

**Comment by 1amageek** [comment]
Toolbar now works with safeArea.
If you want to change the layout, set `additionalSafeAreaInsets`.

```swift
// ViewController
self.additionalSafeAreaInsets
```
https://github.com/1amageek/Toolbar/blob/master/Example/ChatViewController.swift#L75

**Comment by majid701** [comment]
@1amageek thanks for further explanation. It's working now!
